name: Backpacks
version: '${project.version}'
main: com.gmail.ibmesp1.Backpacks
api-version: 1.13
authors: [ Ib ]

commands:
  bp:
    description: Use /bp help to see the commands
  bpsee:
    description: Use /bp help to see the commands
    permission: bp.bpsee
  bgamerule:
    description: Use /bp help to see the commands
    permission: bp.gamerule
    aliases: bgr
